project_id = "dwcdxofvxsmpbziosvbo"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.notify-registration-status]
verify_jwt = false

[functions.seed-demo-data]
verify_jwt = false

[functions.seed-demo-users]
verify_jwt = false

[functions.parse-pdf]
verify_jwt = false
